import { Clock3, Sparkles } from 'lucide-react';

type RecordWithAi = { result: string; confidence: number; analysisData?: { aiAssessment?: { imageQuality: string; referenceCardVisible: boolean; reactionAreaVisible: boolean; lightingConcern: boolean; visualAssessment: string; aiConfidence: number; consistencyWithAlgorithm: string; reviewRecommended: boolean; explanation: string } | null }; aiAnalysis?: string | null; aiConfidence?: number | null; aiConsistency?: string | null; aiReviewRecommended?: boolean; aiExplanation?: string | null; aiModel?: string | null };

export function AiAssessmentPanel({ record }: { record: RecordWithAi }) {
  let assessment = record.analysisData?.aiAssessment ?? null;
  if (!assessment && record.aiAnalysis) { try { assessment = JSON.parse(record.aiAnalysis); } catch { assessment = null; } }
  return <div className="panel ai-record-panel"><div className="panel-heading"><div><p className="eyebrow">Supporting analysis</p><h3>Gemini visual assessment</h3></div><Sparkles size={20} /></div>{assessment ? <><div className="ai-grid"><div><small>Algorithm confidence</small><strong>{Math.round(record.confidence * 100)}%</strong></div><div><small>AI confidence</small><strong>{Math.round(assessment.aiConfidence * 100)}%</strong></div><div><small>Consistency</small><strong>{assessment.consistencyWithAlgorithm}</strong></div><div><small>Image quality</small><strong>{assessment.imageQuality}</strong></div></div><p className="ai-explanation">{assessment.explanation}</p><div className="ai-facts"><span>Reference card: {assessment.referenceCardVisible ? 'Visible' : 'Not confirmed'}</span><span>Reaction area: {assessment.reactionAreaVisible ? 'Visible' : 'Not confirmed'}</span><span>Lighting concern: {assessment.lightingConcern ? 'Yes' : 'No'}</span></div>{assessment.reviewRecommended && <div className="location-note"><Clock3 size={16} /> Supervisor review recommended. The deterministic result remains the official presumptive classification.</div>}</> : <p className="muted">AI supporting analysis is unavailable for this record. The deterministic colour analysis remains the primary result.</p>}</div>;
}
