import { useEffect, useState } from 'react';
import { ArrowLeft, Check, Download, FileCheck2, FileText, ShieldAlert, ShieldCheck, X } from 'lucide-react';
import { API, request } from './auth';

type RecordItem = { id: string; testId: string; operatorId: string; testType: string; result: string; confidence: number; timestamp: string; locationSource: string; reviewStatus: string; verificationStatus: string; verifiedBy?: string | null; imageHash: string; notes: string };
const date = (value: string) => new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
function Badge({ value }: { value: string }) { return <span className={`status ${value.toLowerCase()}`}>{value}</span>; }

export function AccessDenied({ onBack }: { onBack: () => void }) { return <section className="content access-denied"><ShieldAlert size={42} /><p className="eyebrow">403 / Restricted area</p><h1>Access Denied</h1><p>You do not have permission to access this page.</p><button className="primary" onClick={onBack}><ArrowLeft size={16} /> Back to Dashboard</button></section>; }

export function ActivityPage() { const [logs, setLogs] = useState<any[]>([]); const [error, setError] = useState(''); useEffect(() => { request('/activity').then(setLogs).catch((reason) => setError(reason.message)); }, []); return <section className="content"><div className="page-heading"><div><p className="eyebrow">Field operator / audit</p><h1>My activity</h1><p className="muted">Actions recorded against your authenticated account.</p></div></div>{error && <p className="form-error">{error}</p>}<div className="panel activity-timeline">{logs.map((log) => <div className="audit-row" key={log.id}><span /><div><strong>{log.eventType.replace(/_/g, ' ')}</strong><small>{date(log.timestamp)}{log.testId ? ` / ${log.testId}` : ''}</small></div></div>)}{!logs.length && !error && <div className="empty"><FileText size={28} /><h3>No activity recorded</h3><p>Your authenticated actions will appear here.</p></div>}</div></section>; }

export function VerificationPage() { const [records, setRecords] = useState<RecordItem[]>([]); const [message, setMessage] = useState(''); const load = () => { request('/tests').then(setRecords).catch((error) => setMessage(error.message)); }; useEffect(() => { load(); }, []); const verify = async (testId: string) => { try { await request(`/tests/${testId}/verify`); load(); } catch (error) { setMessage((error as Error).message); } }; return <section className="content"><div className="page-heading"><div><p className="eyebrow">Supervisor console</p><h1>Verification</h1><p className="muted">Verify image integrity and bind the supervisor identity to the record.</p></div></div>{message && <p className="form-error">{message}</p>}<div className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Test ID</th><th>Operator</th><th>Review</th><th>Verification</th><th>Verified by</th><th>Action</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><strong>{record.testId}</strong></td><td>{record.operatorId}</td><td><Badge value={record.reviewStatus} /></td><td><Badge value={record.verificationStatus} /></td><td>{record.verifiedBy ?? '-'}</td><td>{record.verificationStatus !== 'VERIFIED' && <button className="approve-button" onClick={() => verify(record.testId)}><ShieldCheck size={14} /> Verify integrity</button>}</td></tr>)}</tbody></table></div></div></section>; }

export function ReviewPage({ onOpen }: { onOpen: (id: string) => void }) { const [records, setRecords] = useState<RecordItem[]>([]); const [message, setMessage] = useState(''); const load = () => { request('/supervisor/reviews').then(setRecords).catch((error) => setMessage(error.message)); }; useEffect(() => { load(); }, []); const review = async (id: string, action: 'approve' | 'reject') => { const reviewComment = window.prompt(`${action === 'approve' ? 'Approval' : 'Rejection'} comment`, '') ?? ''; if (action === 'reject' && !reviewComment) return; await request(`/supervisor/tests/${id}/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reviewComment }) }); load(); }; return <section className="content"><div className="page-heading"><div><p className="eyebrow">Supervisor console</p><h1>Review & approvals</h1><p className="muted">Review pending presumptive field-test records before operational sign-off.</p></div><span className="soft-label">{records.length} PENDING</span></div>{message && <p className="form-error">{message}</p>}<div className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Test ID</th><th>Operator</th><th>Result</th><th>Confidence</th><th>Date / time</th><th>Verification</th><th>Action</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><strong>{record.testId}</strong><small>{record.testType}</small></td><td>{record.operatorId}</td><td><Badge value={record.result} /></td><td>{Math.round(record.confidence * 100)}%</td><td>{date(record.timestamp)}</td><td>{record.verificationStatus}</td><td><div className="row-actions"><button className="approve-button" onClick={() => review(record.testId, 'approve')}><Check size={14} /> Approve</button><button className="reject-button" onClick={() => review(record.testId, 'reject')}><X size={14} /> Reject</button><button className="text-button" onClick={() => onOpen(record.testId)}>View</button></div></td></tr>)}</tbody></table>{!records.length && <div className="empty"><FileCheck2 size={28} /><h3>No pending reviews</h3><p>New records requiring supervisor review will appear here.</p></div>}</div></div></section>; }

export function SupervisorAnalytics() { const [data, setData] = useState<any>(null); useEffect(() => { request('/supervisor/analytics').then(setData); }, []); if (!data) return <section className="content"><div className="loading-screen">Loading supervisor analytics...</div></section>; return <section className="content"><div className="page-heading"><div><p className="eyebrow">Supervisor console</p><h1>Expanded analytics</h1><p className="muted">All-operator trends, review state and verification health.</p></div></div><div className="analytics-cards"><div className="panel big-number"><span>Total tests</span><strong>{data.total}</strong><small>Across the field unit</small></div><div className="panel big-number"><span>Pending reviews</span><strong>{data.review.pending}</strong><small>Require supervisor action</small></div><div className="panel big-number"><span>Exceptions</span><strong>{data.verificationExceptions}</strong><small>Integrity or metadata issues</small></div></div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Results</p><h3>Distribution</h3></div></div><div className="legend"><div>Positive <strong>{data.results.positive}</strong></div><div>Negative <strong>{data.results.negative}</strong></div><div>Inconclusive <strong>{data.results.inconclusive}</strong></div></div></div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Operators</p><h3>Tests by operator</h3></div></div><div className="legend">{Object.entries(data.byOperator).map(([operator, count]) => <div key={operator}>{operator}<strong>{String(count)}</strong></div>)}</div></div></div></section>; }

export function ExceptionsPage() { const [exceptions, setExceptions] = useState<any[]>([]); const load = () => { request('/supervisor/exceptions').then(setExceptions); }; useEffect(() => { load(); }, []); const create = async () => { const testId = window.prompt('Test ID'); const reason = window.prompt('Exception reason'); if (!testId || !reason) return; await request('/supervisor/exceptions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ testId, reason }) }); load(); }; const resolve = async (id: string) => { const resolution = window.prompt('Resolution'); if (!resolution) return; await request(`/supervisor/exceptions/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'RESOLVED', resolution }) }); load(); }; return <section className="content"><div className="page-heading"><div><p className="eyebrow">Supervisor console</p><h1>Verification exceptions</h1><p className="muted">Track integrity failures, incomplete metadata and inconclusive reviews.</p></div><button className="primary" onClick={create}><ShieldAlert size={16} /> Create exception</button></div><div className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Test ID</th><th>Reason</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{exceptions.map((item) => <tr key={item.id}><td><strong>{item.testId}</strong></td><td>{item.reason}</td><td><Badge value={item.status} /></td><td>{date(item.createdAt)}</td><td>{item.status !== 'RESOLVED' && <button className="approve-button" onClick={() => resolve(item.id)}><Check size={14} /> Resolve</button>}</td></tr>)}</tbody></table>{!exceptions.length && <div className="empty"><ShieldCheck size={28} /><h3>No exceptions</h3><p>The verification queue is clear.</p></div>}</div></div></section>; }

export function AuditPage() { const [logs, setLogs] = useState<any[]>([]); useEffect(() => { request('/supervisor/audit').then(setLogs); }, []); return <section className="content"><div className="page-heading"><div><p className="eyebrow">Supervisor console</p><h1>Audit trail</h1><p className="muted">Complete activity across operators, records and security events.</p></div></div><div className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Event</th><th>User</th><th>Role</th><th>Test</th><th>Timestamp</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id}><td><strong>{log.eventType}</strong></td><td>{log.user.operatorId}</td><td>{log.user.role}</td><td>{log.testId ?? '-'}</td><td>{date(log.timestamp)}</td></tr>)}</tbody></table></div></div></section>; }

export function ExportPage() { const [busy, setBusy] = useState(false); const download = async () => { setBusy(true); try { const token = localStorage.getItem('fieldverify-token'); const response = await fetch(`${API}/supervisor/export`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Export failed'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'fieldverify-audit-report.csv'; anchor.click(); URL.revokeObjectURL(url); } finally { setBusy(false); } }; return <section className="content"><div className="page-heading"><div><p className="eyebrow">Supervisor console</p><h1>Audit reports</h1><p className="muted">Export a complete CSV record for review and presentation.</p></div></div><div className="workflow-card"><FileText size={34} /><h2>Complete audit report</h2><p className="muted">Includes tests, GPS, hashes, signatures, review state and audit events.</p><button className="primary" onClick={download} disabled={busy}><Download size={17} /> {busy ? 'Preparing report...' : 'Download CSV report'}</button></div></section>; }
